### ISSUE TITLE
[HPC][NWays] MD Mini Challenge CUDA C MakeFile Bug 

### ISSUE THREAD

**Issue by programmah** [gpuhackathons-org/gpubootcamp#55] opened 2021-07-28 05:12 UTC
MakeFile works with CUDA 11.0 but breaks with CUDA 11.2 version.

**Sample error found when using the MakeFile to run the  CUDA C  MD mini-challenge :**
nvcc  nvlink fatal  : Input file 
'/opt/nvidia/hpc_sdk/Linux_x86_64/21.3/cuda/11.2/lib64/libcudadevrt.a:cuda_device_runtime.o' newer than toolkit (112 vs 110)

**Comment by bharatk-parallel** [comment] 2021-09-09 05:48
Closing as not able to reproduce. Tested with Docker and Singularity in two different clusters. Fixed the CUDA-C path folder issue.

**Closed by bharatk-parallel** 2021-09-09 05:48 UTC
Labels: bug
